### ISSUE TITLE
Support deny list for folders in order to skip parsing dbt packages

### ISSUE THREAD

**Issue by jsnb-devoted** [AltimateAI/vscode-dbt-power-user#1360]
### Describe the feature

I see you have an "Allow List Folders" config but we could use a deny list as well. We are getting errors from the extension like this:
```
Skipping project: could not parse dbt_project_config.yml at 'file:///.../core/data/dbt/packages/dbt_artifacts/integration_test_project': Error: Illegal argument: base
```
Our project is at `core/data/dbt` and our packages are installed at `core/data/dbt/packages`. If I could deny the `core/data/dbt/packages` folder that would be a huge help in suppressing these errors.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Actually that is supposed to work out of the box. We should filter out the projects that are in the packages folder.

Could you debug following code a bit and let me know your findings?

https://github.com/AltimateAI/vscode-dbt-power-user/blob/4e7b9d55a6ef8c08147e0157ebd8d277eaa6ddf2/src/dbt_client/dbtCoreIntegration.ts#L219-L223

**Comment by mdesmet** [comment]
If this issue is new, it might also be fixed by https://github.com/AltimateAI/vscode-dbt-power-user/pull/1361

**Comment by jsnb-devoted** [comment]
It's not urgent -- I can wait until the next release. I was a few versions back and when I upgraded to the latest from today I get this error:
```
2024-08-12 20:42:10.055 [error] Error: sourcePaths is not defined in project in /home/jbrownstein/go/src/github.com/DevotedHealth/core/data/dbt
	at SourceFileWatchers.onProjectConfigChanged (/home/jbrownstein/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.44.0/dist/extension.js:21350:40)
	at p.value (/home/jbrownstein/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.44.0/dist/extension.js:21336:116)
	at n.y (/home/jbrownstein/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/workbench/api/node/extensionHostProcess.js:80:1902)
	at n.z (/home/jbrownstein/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/workbench/api/node/extensionHostProcess.js:80:1972)
	at n.fire (/home/jbrownstein/.vscode-server/bin/863d2581ecda6849923a2118d93a088b0745d9d6/out/vs/workbench/api/node/extensionHostProcess.js:80:2188)
	at DBTProject.<anonymous> (/home/jbrownstein/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.44.0/dist/extension.js:20380:36)
	at Generator.throw (<anonymous>)
	at rejected (/home/jbrownstein/.vscode-server/extensions/innoverio.vscode-dbt-power-user-0.44.0/dist/extension.js:26973:28)	
```
I'll keep an eye on #1361 and upgrade when it gets released

**Comment by mdesmet** [comment]
This is just a log line, it might be incorrectly advertised as error, should be warning, is there any error being displayed or anything that is not acutally working

**Comment by jsnb-devoted** [comment]
This seems to be working after taking the latest upgrade 👍
