### ISSUE TITLE
dbt power user compile/build/run encounters error

### ISSUE THREAD

**Issue by FDG4663** [AltimateAI/vscode-dbt-power-user#1474]
### Expected behavior

The file should be compiled/run/built. No changes to dbt scripts, project config, or dbt power user settings.
I have tried

### Actual behavior

I am getting a deserialization error in __mashumaro_from_dict__ and no compliation, running or building is happening. 

### Steps To Reproduce

I'm not sure about how create a mwe. maybe you know a public dbt project I can try compliling/building in to check whether the issue persists

### Log output/Screenshots

```
Encountered an error:
Field "results" of type Sequence[RunResultOutput] in RunResultsArtifact has invalid value [{'status': 'success', 'timing': [{'name': 'elementary.on-run-start.0', 'started_at': '2024-10-21T11:25:59.001037Z', 'completed_at': '2024-10-21T11:26:00.748834Z'}], 'thread_id': 'main', 'execution_time': 1.747797, 'adapter_response': {}, 'message': 'elementary.on-run-start.0 passed', 'failures': 0, 'unique_id': 'operation.elementary.elementary-on-run-start-0', 'compiled': True, 'compiled_code': '\n  \n  \n\n  \n  \n\n  \n    \n  \n', 'relation_name': None, 'batch_results': None}, {'status': 'success', 'timing': [{'name': 'compile', 'started_at': '2024-10-21T11:26:00.754781Z', 'completed_at': '2024-10-21T11:26:00.757556Z'}, {'name': 'execute', 'started_at': '2024-10-21T11:26:00.757964Z', 'completed_at': '2024-10-21T11:26:02.157927Z'}], 'thread_id': 'Thread-1 (worker)', 'execution_time': 1.404050350189209, 'adapter_response': {'_message': 'SUCCESS 1', 'code': 'SUCCESS', 'rows_affected': 1, 'query_id': '01b7d64e-0204-c321-0001-075a0b5ff51e'}, 'message': 'SUCCESS 1', 'failures': None, 'unique_id': 'model.GB_Domain_Commercial.rep_rebolution_FACT_AR_AP_AFR', 'compiled': True, 'compiled_code': "with\n\n--#########  SOURCES  #########\n\nFACT_AR_AP as(\n    select * from DB_GBANALYTICS_DEV.DBT_FDAQ_SH_DRV.FACT_AR_AP\n),\n\nV_DIM_COUNTRY_BU as (\n    select * from DB_GBANALYTICS_PRD.SH_DRV.V_DIM_COUNTRY_BU\n),\n\n--#########  TRANSFORMATION  #########\n\nONLY_GBU_AFRICA as (\n    select \n        f.*\n    from FACT_AR_AP f\n    join V_DIM_COUNTRY_BU b\n        on f.country_bu_code = b.country_bu_code\n    -- AFRICA GBU\n    where b.grand_business_unit_code in ('1004')\n),\n\nONLY_USED_AFRICA_KPIS as (\n    select \n        ACCOUNTING_FLAG,\n        -- ACCOUNTING_TYPE,\n        -- ACCOUNT_TYPE,\n        -- BAD_DEBT,                  -- EUROPE\n        -- BALANCE_DEFEATED,          -- EUROPE\n        BALANCE_DEFEATED_AFR,\n        -- BILLING_TYPE,\n        COMPANY_CODE,                 -- FK_DIM_PAYER, FK_DIM_SOLD_TO (debugging)\n        COUNTRY_BU_CODE,\n        -- CREDIT_NOTE,               -- EUROPE\n        DEBT_0_10,\n        DEBT_11_30,\n        DEBT_120_PLUS,\n        -- DEBT_30DAYS,               -- EUROPE\n        DEBT_31_60,\n        -- DEBT_60DAYS,               -- EUROPE\n        DEBT_61_90,\n        -- DEBT_90DAYS,               -- EUROPE\n        DEBT_91_120,\n        DEBT_ANTIQUITY_DENOMINATOR,\n        DEBT_ANTIQUITY_NOMINATOR,\n        -- DEDUCTION,                 -- EUROPE\n        DISTRIBUTION_CHANNEL_ID,      -- FK_DIM_PAYER, FK_DIM_SOLD_TO (debugging)\n        FK_DIM_PAYER,\n        FK_DIM_SOLD_TO,\n        FISCAL_PERIOD,\n        GL_ACCOUNT,\n        LAST_DAY_FISCAL_PERIOD,\n        LOAD_TIMESTAMP,               -- EXCLUDE in power query\n        -- LOCAL_CURRENCY,\n        -- NET_SALES,                 -- EUROPE\n        -- NET_VALUE,                 -- EUROPE\n        NEW_INVOICES_AFR,\n        NEW_PAYMENTS_AFR,\n        -- ORDER_REASON_CODE,\n        PAYER_ID,                     -- FK_DIM_PAYER (debugging)\n        -- PAYER_ID_DESCRIPTION,\n        PK_FACT_AR_AP,\n        -- PRICE_DIFFERENCE_FLAG,     -- EUROPE\n        -- PROMO_INVOICE,             -- EUROPE\n        -- QUANTITY_DIFFERENCE_FLAG,  -- EUROPE\n        -- RETURN_FLAG,               -- EUROPE\n        -- RIBA,                      -- EUROPE\n        SOLD_TO_ID,                   -- FK_DIM_SOLD_TO (debugging)\n        -- SOLD_TO_ID_DESCRIPTION,\n        -- TOTAL_AMOUNT,              -- EUROPE\n        TOTAL_DEBT_AFR\n    from ONLY_GBU_AFRICA\n),\n\nFINAL as (\n    select\n    * exclude (LOAD_TIMESTAMP)\n    ,current_timestamp(2) as LOAD_TIMESTAMP\n    from ONLY_USED_AFRICA_KPIS\n)\n\n--#########  FINAL  #########\nselect * from FINAL", 'relation_name': 'DB_GBANALYTICS_DEV.DBT_FDAQ_SH_REP.V_FACT_AR_AP_AFR', 'batch_results': None}, {'status': 'pass', 'timing': [{'name': 'compile', 'started_at': '2024-10-21T11:26:02.165000Z', 'completed_at': '2024-10-21T11:26:02.182768Z'}, {'name': 'execute', 'started_at': '2024-10-21T11:26:02.183213Z', 'completed_at': '2024-10-21T11:26:03.226727Z'}], 'thread_id': 'Thread-3 (worker)', 'execution_time': 1.0636534690856934, 'adapter_response': {'_message': 'SUCCESS 1', 'code': 'SUCCESS', 'rows_affected': 1, 'query_id': '01b7d64e-0204-c2e8-0001-075a0b5feb2e'}, 'message': None, 'failures': 0, 'unique_id': 'test.GB_Domain_Commercial.not_null_rep_rebolution_FACT_AR_AP_AFR_PK_FACT_AR_AP.12bcd4e314', 'compiled': True, 'compiled_code': '\n    \n    \n\n\n\nselect PK_FACT_AR_AP\nfrom DB_GBANALYTICS_DEV.DBT_FDAQ_SH_REP.V_FACT_AR_AP_AFR\nwhere PK_FACT_AR_AP is null\n\n\n', 'relation_name': None, 'batch_results': None}, {'status': 'pass', 'timing': [{'name': 'compile', 'started_at': '2024-10-21T11:26:02.176102Z', 'completed_at': '2024-10-21T11:26:02.194748Z'}, {'name': 'execute', 'started_at': '2024-10-21T11:26:02.195310Z', 'completed_at': '2024-10-21T11:26:04.181896Z'}], 'thread_id': 'Thread-4 (worker)', 'execution_time': 2.0183379650115967, 'adapter_response': {'_message': 'SUCCESS 1', 'code': 'SUCCESS', 'rows_affected': 1, 'query_id': '01b7d64e-0204-c2e8-0001-075a0b5feb2a'}, 'message': None, 'failures': 0, 'unique_id': 'test.GB_Domain_Commercial.unique_rep_rebolution_FACT_AR_AP_AFR_PK_FACT_AR_AP.aa487c8617', 'compiled': True, 'compiled_code': '\n    \n    \n\nselect\n    PK_FACT_AR_AP as unique_field,\n    count(*) as n_records\n\nfrom DB_GBANALYTICS_DEV.DBT_FDAQ_SH_REP.V_FACT_AR_AP_AFR\nwhere PK_FACT_AR_AP is not null\ngroup by PK_FACT_AR_AP\nhaving count(*) > 1\n\n\n', 'relation_name': None, 'batch_results': None}, {'status': 'success', 'timing': [{'name': 'elementary.on-run-end.0', 'started_at': '2024-10-21T11:26:04.184805Z', 'completed_at': '2024-10-21T11:26:04.952912Z'}], 'thread_id': 'main', 'execution_time': 0.768107, 'adapter_response': {}, 'message': 'elementary.on-run-end.0 passed', 'failures': 0, 'unique_id': 'operation.elementary.elementary-on-run-end-0', 'compiled': True, 'compiled_code': '\n      \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n      \n        \n      \n  \n', 'relation_name': None, 'batch_results': None}], Traceback (most recent call last):
  File "<string>", line 10, in __mashumaro_from_dict__
  File "<string>", line 9, in __unpack_literal_TimingInfo_name__c89858ba687f41d4a30b856eeb3efdf8
ValueError: elementary.on-run-start.0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "<string>", line 17, in <listcomp>
  File "<string>", line 4, in __mashumaro_from_dict__
  File "<string>", line 12, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "name" of type Literal['compile', 'execute', 'other'] in TimingInfo has invalid value 'elementary.on-run-start.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 17, in __mashumaro_from_dict__
  File "<string>", line 17, in <listcomp>
  File "<string>", line 4, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "timing" of type List[TimingInfo] in RunResultOutput has invalid value [{'name': 'elementary.on-run-start.0', 'started_at': '2024-10-21T11:25:59.001037Z', 'completed_at': '2024-10-21T11:26:00.748834Z'}]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/requires.py", line 221, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/requires.py", line 131, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/requires.py", line 329, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/requires.py", line 356, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/requires.py", line 404, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/requires.py", line 426, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/cli/main.py", line 337, in compile
    task = CompileTask(
           ^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/task/runnable.py", line 106, in __init__
    self.previous_state = PreviousState(
                          ^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/contracts/state.py", line 47, in __init__
    self.results = load_result_state(results_path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/contracts/state.py", line 16, in load_result_state
    return RunResultsArtifact.read_and_check_versions(str(results_path))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/artifacts/schemas/base.py", line 137, in read_and_check_versions
    return cls.upgrade_schema_version(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/dbt-versionless/lib/python3.11/site-packages/dbt/artifacts/schemas/run/v5/run.py", line 179, in upgrade_schema_version
    return cls.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^
  File "<string>", line 4, in __mashumaro_from_dict__
  File "<string>", line 19, in __mashumaro_from_dict__
mashumaro.exceptions.InvalidFieldValue: Field "results" of type Sequence[RunResultOutput] in RunResultsArtifact has invalid value [{'status': 'success', 'timing': [{'name': 'elementary.on-run-start.0', 'started_at': '2024-10-21T11:25:59.001037Z', 'completed_at': '2024-10-21T11:26:00.748834Z'}], 'thread_id': 'main', 'execution_time': 1.747797, 'adapter_response': {}, 'message': 'elementary.on-run-start.0 passed', 'failures': 0, 'unique_id': 'operation.elementary.elementary-on-run-start-0', 'compiled': True, 'compiled_code': '\n  \n  \n\n  \n  \n\n  \n    \n  \n', 'relation_name': None, 'batch_results': None}, {'status': 'success', 'timing': [{'name': 'compile', 'started_at': '2024-10-21T11:26:00.754781Z', 'completed_at': '2024-10-21T11:26:00.757556Z'}, {'name': 'execute', 'started_at': '2024-10-21T11:26:00.757964Z', 'completed_at': '2024-10-21T11:26:02.157927Z'}], 'thread_id': 'Thread-1 (worker)', 'execution_time': 1.404050350189209, 'adapter_response': {'_message': 'SUCCESS 1', 'code': 'SUCCESS', 'rows_affected': 1, 'query_id': '01b7d64e-0204-c321-0001-075a0b5ff51e'}, 'message': 'SUCCESS 1', 'failures': None, 'unique_id': 'model.GB_Domain_Commercial.rep_rebolution_FACT_AR_AP_AFR', 'compiled': True, 'compiled_code': "with\n\n--#########  SOURCES  #########\n\nFACT_AR_AP as(\n    select * from DB_GBANALYTICS_DEV.DBT_FDAQ_SH_DRV.FACT_AR_AP\n),\n\nV_DIM_COUNTRY_BU as (\n    select * from DB_GBANALYTICS_PRD.SH_DRV.V_DIM_COUNTRY_BU\n),\n\n--#########  TRANSFORMATION  #########\n\nONLY_GBU_AFRICA as (\n    select \n        f.*\n    from FACT_AR_AP f\n    join V_DIM_COUNTRY_BU b\n        on f.country_bu_code = b.country_bu_code\n    -- AFRICA GBU\n    where b.grand_business_unit_code in ('1004')\n),\n\nONLY_USED_AFRICA_KPIS as (\n    select \n        ACCOUNTING_FLAG,\n        -- ACCOUNTING_TYPE,\n        -- ACCOUNT_TYPE,\n        -- BAD_DEBT,                  -- EUROPE\n        -- BALANCE_DEFEATED,          -- EUROPE\n        BALANCE_DEFEATED_AFR,\n        -- BILLING_TYPE,\n        COMPANY_CODE,                 -- FK_DIM_PAYER, FK_DIM_SOLD_TO (debugging)\n        COUNTRY_BU_CODE,\n        -- CREDIT_NOTE,               -- EUROPE\n        DEBT_0_10,\n        DEBT_11_30,\n        DEBT_120_PLUS,\n        -- DEBT_30DAYS,               -- EUROPE\n        DEBT_31_60,\n        -- DEBT_60DAYS,               -- EUROPE\n        DEBT_61_90,\n        -- DEBT_90DAYS,               -- EUROPE\n        DEBT_91_120,\n        DEBT_ANTIQUITY_DENOMINATOR,\n        DEBT_ANTIQUITY_NOMINATOR,\n        -- DEDUCTION,                 -- EUROPE\n        DISTRIBUTION_CHANNEL_ID,      -- FK_DIM_PAYER, FK_DIM_SOLD_TO (debugging)\n        FK_DIM_PAYER,\n        FK_DIM_SOLD_TO,\n        FISCAL_PERIOD,\n        GL_ACCOUNT,\n        LAST_DAY_FISCAL_PERIOD,\n        LOAD_TIMESTAMP,               -- EXCLUDE in power query\n        -- LOCAL_CURRENCY,\n        -- NET_SALES,                 -- EUROPE\n        -- NET_VALUE,                 -- EUROPE\n        NEW_INVOICES_AFR,\n        NEW_PAYMENTS_AFR,\n        -- ORDER_REASON_CODE,\n        PAYER_ID,                     -- FK_DIM_PAYER (debugging)\n        -- PAYER_ID_DESCRIPTION,\n        PK_FACT_AR_AP,\n        -- PRICE_DIFFERENCE_FLAG,     -- EUROPE\n        -- PROMO_INVOICE,             -- EUROPE\n        -- QUANTITY_DIFFERENCE_FLAG,  -- EUROPE\n        -- RETURN_FLAG,               -- EUROPE\n        -- RIBA,                      -- EUROPE\n        SOLD_TO_ID,                   -- FK_DIM_SOLD_TO (debugging)\n        -- SOLD_TO_ID_DESCRIPTION,\n        -- TOTAL_AMOUNT,              -- EUROPE\n        TOTAL_DEBT_AFR\n    from ONLY_GBU_AFRICA\n),\n\nFINAL as (\n    select\n    * exclude (LOAD_TIMESTAMP)\n    ,current_timestamp(2) as LOAD_TIMESTAMP\n    from ONLY_USED_AFRICA_KPIS\n)\n\n--#########  FINAL  #########\nselect * from FINAL", 'relation_name': 'DB_GBANALYTICS_DEV.DBT_FDAQ_SH_REP.V_FACT_AR_AP_AFR', 'batch_results': None}, {'status': 'pass', 'timing': [{'name': 'compile', 'started_at': '2024-10-21T11:26:02.165000Z', 'completed_at': '2024-10-21T11:26:02.182768Z'}, {'name': 'execute', 'started_at': '2024-10-21T11:26:02.183213Z', 'completed_at': '2024-10-21T11:26:03.226727Z'}], 'thread_id': 'Thread-3 (worker)', 'execution_time': 1.0636534690856934, 'adapter_response': {'_message': 'SUCCESS 1', 'code': 'SUCCESS', 'rows_affected': 1, 'query_id': '01b7d64e-0204-c2e8-0001-075a0b5feb2e'}, 'message': None, 'failures': 0, 'unique_id': 'test.GB_Domain_Commercial.not_null_rep_rebolution_FACT_AR_AP_AFR_PK_FACT_AR_AP.12bcd4e314', 'compiled': True, 'compiled_code': '\n    \n    \n\n\n\nselect PK_FACT_AR_AP\nfrom DB_GBANALYTICS_DEV.DBT_FDAQ_SH_REP.V_FACT_AR_AP_AFR\nwhere PK_FACT_AR_AP is null\n\n\n', 'relation_name': None, 'batch_results': None}, {'status': 'pass', 'timing': [{'name': 'compile', 'started_at': '2024-10-21T11:26:02.176102Z', 'completed_at': '2024-10-21T11:26:02.194748Z'}, {'name': 'execute', 'started_at': '2024-10-21T11:26:02.195310Z', 'completed_at': '2024-10-21T11:26:04.181896Z'}], 'thread_id': 'Thread-4 (worker)', 'execution_time': 2.0183379650115967, 'adapter_response': {'_message': 'SUCCESS 1', 'code': 'SUCCESS', 'rows_affected': 1, 'query_id': '01b7d64e-0204-c2e8-0001-075a0b5feb2a'}, 'message': None, 'failures': 0, 'unique_id': 'test.GB_Domain_Commercial.unique_rep_rebolution_FACT_AR_AP_AFR_PK_FACT_AR_AP.aa487c8617', 'compiled': True, 'compiled_code': '\n    \n    \n\nselect\n    PK_FACT_AR_AP as unique_field,\n    count(*) as n_records\n\nfrom DB_GBANALYTICS_DEV.DBT_FDAQ_SH_REP.V_FACT_AR_AP_AFR\nwhere PK_FACT_AR_AP is not null\ngroup by PK_FACT_AR_AP\nhaving count(*) > 1\n\n\n', 'relation_name': None, 'batch_results': None}, {'status': 'success', 'timing': [{'name': 'elementary.on-run-end.0', 'started_at': '2024-10-21T11:26:04.184805Z', 'completed_at': '2024-10-21T11:26:04.952912Z'}], 'thread_id': 'main', 'execution_time': 0.768107, 'adapter_response': {}, 'message': 'elementary.on-run-end.0 passed', 'failures': 0, 'unique_id': 'operation.elementary.elementary-on-run-end-0', 'compiled': True, 'compiled_code': '\n      \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n        \n      \n\n      \n      \n        \n      \n  \n', 'relation_name': None, 'batch_results': None}]
```

### Operating System

Windows 11

### dbt version

dbt Cloud CLI - 0.38.18

### dbt Adapter

dbt cloud cli

### dbt Power User version

0.47.0 to 0.47.4

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
Does it work when you try running it using dbt cli command?

You should be able to see the command that the dbt cli command that the extension executes in the debug logs : https://docs.myaltimate.com/trobleshooting/#check-extension-logs

**Comment by FDG4663** [comment]
For some reason today it is working (I haven't even restarted VSCode). I guess something in network or API has reset or timed out.
