### ISSUE TITLE
dbt Power User can't find snowflake.connector module

### ISSUE THREAD

**Issue by jaredparco** [AltimateAI/vscode-dbt-power-user#841]
### Expected behavior

When using any features that invoke a command in the terminal (dbt run, dbt build, dbt test) no errors are produced

### Actual behavior

When using any features that invoke a command in the terminal (dbt run, dbt build, dbt test) through vscode-dbt-power-user, an error results in the terminal.

### Steps To Reproduce

Clicking on the 'Build dbt Model', 'Run dbt Model', 'Test dbt Model' icons in vscode. 

### Log output/Screenshots

```
21:20:55  Running with dbt=1.6.9
21:20:55  Encountered an error:
No module named 'snowflake.connector'
21:20:55  Traceback (most recent call last):
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/cli/requires.py", line 87, in wrapper
    result, success = func(*args, **kwargs)
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/cli/requires.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/cli/requires.py", line 140, in wrapper
    profile = load_profile(flags.PROJECT_DIR, flags.VARS, flags.PROFILE, flags.TARGET, threads)
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/config/runtime.py", line 70, in load_profile
    profile = Profile.render(
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/config/profile.py", line 436, in render
    return cls.from_raw_profiles(
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/config/profile.py", line 401, in from_raw_profiles
    return cls.from_raw_profile_info(
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/config/profile.py", line 355, in from_raw_profile_info
    credentials: Credentials = cls._credentials_from_profile(
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/config/profile.py", line 165, in _credentials_from_profile
    cls = load_plugin(typename)
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/adapters/factory.py", line 212, in load_plugin
    return FACTORY.load_plugin(name)
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/adapters/factory.py", line 58, in load_plugin
    mod: Any = import_module("." + name, "dbt.adapters")
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/adapters/snowflake/__init__.py", line 2, in <module>
    from dbt.adapters.snowflake.connections import SnowflakeConnectionManager  # noqa
  File "/home/appuser/anaconda3/envs/py39/lib/python3.9/site-packages/dbt/adapters/snowflake/connections.py", line 17, in <module>
    import snowflake.connector
ModuleNotFoundError: No module named 'snowflake.connector'
```

### Operating System

Sonoma 14.1 (23B74)

### dbt version

1.6.9

### dbt Adapter

snowflake

### dbt Power User version

0.29.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jaredparco** [comment]
As a note, when we run dbt in the python environment outside of vscode in terminal, we encounter no errors. It is only when running it through vscode that we encounter an error

**Comment by anandgupta42** [comment]
@jaredparco It appears that there is an issue with your Python environment, and it seems that the Snowflake adapter is not installed correctly. To resolve this issue, you can try creating a new Python virtual environment and perform a fresh installation of the Snowflake adapter. After doing so, you can check if the issue has been resolved.

**Comment by anandgupta42** [comment]
The terminal may not use the same Python environment as the extension. The setup walkthrough may help you resolve the issue as well: https://docs.myaltimate.com/setup/installation/.

**Comment by jaredparco** [comment]
thanks. Checking the environment, it looks like it is the same environment between the interpreter vscode is using and the activated environment installed to the docker instance. I'll try creating a clean environment with the dot-snowflake adapter and see if that resolves the issue

**Comment by jaredparco** [comment]
Just created a new Conda environment and installed dbt-snowflake==1.6.6. I switched to the new environment in vscode and am still getting the same error. Here is the installed pip packages:

```
Package                    Version
-------------------------- ------------
agate                      1.7.1
annotated-types            0.6.0
asn1crypto                 1.5.1
attrs                      23.2.0
Babel                      2.14.0
certifi                    2023.11.17
cffi                       1.16.0
charset-normalizer         3.3.2
click                      8.1.7
colorama                   0.4.6
cryptography               41.0.7
dbt-core                   1.6.9
dbt-extractor              0.4.1
dbt-semantic-interfaces    0.2.3
dbt-snowflake              1.6.6
filelock                   3.13.1
hologram                   0.0.16
idna                       3.6
importlib-metadata         6.11.0
isodate                    0.6.1
jaraco.classes             3.3.0
jeepney                    0.8.0
Jinja2                     3.1.3
jsonschema                 4.21.0
jsonschema-specifications  2023.12.1
keyring                    24.3.0
leather                    0.3.4
Logbook                    1.5.3
MarkupSafe                 2.1.3
mashumaro                  3.8.1
minimal-snowplow-tracker   0.0.2
more-itertools             8.14.0
msgpack                    1.0.7
networkx                   3.2.1
packaging                  23.2
parsedatetime              2.6
pathspec                   0.11.2
pip                        23.3.1
platformdirs               3.11.0
protobuf                   4.25.2
pycparser                  2.21
pydantic                   1.10.13
pydantic_core              2.14.6
PyJWT                      2.8.0
pyOpenSSL                  23.3.0
python-dateutil            2.8.2
python-slugify             8.0.1
pytimeparse                1.1.8
pytz                       2023.3.post1
PyYAML                     6.0.1
referencing                0.32.1
requests                   2.31.0
rpds-py                    0.17.1
SecretStorage              3.3.3
setuptools                 68.2.2
six                        1.16.0
snowflake-connector-python 3.6.0
sortedcontainers           2.4.0
sqlparse                   0.4.4
text-unidecode             1.3
tomlkit                    0.12.3
typing_extensions          4.9.0
urllib3                    1.26.18
wheel                      0.41.2
zipp                       3.17.0

```

The error is the same as reported above.

What else am I missing?

**Comment by anandgupta42** [comment]
Can you please check if you have set the variable "dbtPythonPathOverride" in the extension settings?

**Comment by jaredparco** [comment]
No variable is set

**Comment by anandgupta42** [comment]
Can you open a python shell from the env stored at /home/appuser/anaconda3/envs/py39/ and then run 
```
import snowflake.connector

**Comment by jaredparco** [comment]
unsuccessful. I think there may be a snowflake.py that exists somewhere in our python project. I'm wondering if this is creating a conflict. I'll keep you posted

**Comment by jaredparco** [comment]
I've renamed any conflicting file names, reinstalled environment, restarted computer and then did the following

trying 
`import snowflake.connector `
does not work, but 
`import snowflake`
does

**Comment by anandgupta42** [comment]
It more of an issue with snowflake python library and your python environment. I am quite confident that once you resolve this issue the extension should start working.

I found [this thread](https://getdbt.slack.com/archives/C01MSBV7A8Z/p1669715638617669) in the dbt community slack channel. Seems relevant to the problem you are facing.

**Comment by jaredparco** [comment]
thank you I will explore this route
